// This file is generated by npm run build:icons

export type IconName =
  | "arrow"
  | "check"
  | "close"
  | "comment"
  | "github"
  | "link"
  | "location"
  | "login"
  | "logout"
  | "plus-circle"
  | "search"
  | "settings"
  | "threeDots"
  | "x";
